"""Builds script_ai.json (v2, long edition) from the v1 script: keeps ids a00..a56 for kept shots,
inserts empire shots (e01-e08), model-generation shots (e10-e16), replaces the scenario (a36-a49) with the 2027 scenario (f01-f14)."""
import json
V1=json.load(open('script_v1.json'))
S=lambda id,label,year,say:dict(id=id,label=label,year=year,say=say)
byid={s['id']:s for c in V1 for s in c['shots']}
chs={c['ch']:c for c in V1}

E={}
E['e01']=S('e01','BIBLE','c. 603 BC',"Daniel told the king what each part of the statue meant. To Nebuchadnezzar he said, you are the head of gold. That one is certain, because the Bible names it. The Babylonian Empire ruled from the city of Babylon, and under Nebuchadnezzar it stretched from the Persian Gulf to the Mediterranean. Its great gates, and the legend of its hanging gardens, were wonders of the ancient world.")
E['e02']=S('e02','FACT','539 BC',"After you, Daniel said, another kingdom will arise, inferior to yours. The chest and arms of silver. Nearly every tradition agrees that this is the Medo Persian Empire. In five thirty nine B C, Cyrus the Great of Persia took Babylon, on the very night of the writing on the wall. The Persian Empire became the largest the world had yet seen, from India to Egypt, and it stood until three thirty B C.")
E['e03']=S('e03','FACT','334–323 BC',"Then a third kingdom, of bronze, that would rule over all the earth. This is Greece. Later in the book, Daniel names Greece outright. Alexander the Great, a young king of Macedon, crushed the Persian armies and conquered the known world in about a decade. He died in three twenty three B C, and his empire split among his generals.")
E['e04']=S('e04','FACT','146 BC – AD 476',"The fourth kingdom, strong as iron, that breaks and crushes everything. Christians have long identified this as Rome. Rome conquered Greece in one forty six B C, and went on to rule the entire Mediterranean world. Many readers note that the statue has two legs, like the Eastern and Western Roman empires, which split in the year three ninety five. The West fell in four seventy six. The East, called Byzantium, lasted until fourteen fifty three.")
E['e05']=S('e05','INTERPRETATION','The feet',"But the statue does not end with Rome. Its feet and toes were part iron and part clay. A kingdom that is divided, partly strong and partly brittle. They will mix themselves with the seed of men, Daniel said, but they will not hold together, just as iron does not mix with clay. Here the history stops, and the interpretation begins. Nobody agrees on who the feet are.")
E['e06']=S('e06','INTERPRETATION','The ten toes',"The most famous interpretation, held by many Christians for centuries, is that the feet are a revived form of Rome. Not one empire, but a union of ten kingdoms, the ten toes, which Daniel's later vision of ten horns seems to echo. In the Middle Ages, people saw this in the divided kingdoms of Europe. Since nineteen fifty seven, when the Treaty of Rome was signed, some have pointed to the European Union. Others say the ten kings are still in the future, and will rise in the last days. This is a theory, not a fact.")
E['e07']=S('e07','INTERPRETATION','The feet',"Other Christians disagree. Some say the feet are the divided heirs of Rome, including the Islamic empires. Others say the iron and clay are simply the age of nations, from Rome's fall until Christ returns. And some scholars believe the whole prophecy ended with Greece, in the second century B C. In every reading, the ending is the same. The stone strikes the feet, and every kingdom falls at once.")
E['e08']=S('e08','INTERPRETATION','c. 553 BC',"Daniel's beasts match the statue. A lion with eagle's wings, for Babylon. A bear, raised on one side, for Persia. A leopard with four wings and four heads, for Greece, whose empire split into four. And a terrible beast with iron teeth and ten horns, for Rome, and for whatever comes after it. That last beast is the one that Christians have argued about the most.")

E['e10']=S('e10','FACT','2018–2026',"Here is the lineage, in order. OpenAI. G P T one in June twenty eighteen. G P T two in February twenty nineteen. G P T three in twenty twenty. Then Chat G P T, and G P T four in March twenty twenty three. G P T four o in twenty twenty four, and the o one reasoning model. G P T five in August twenty twenty five, and G P T five point two in December.")
E['e10b']=S('e10b','FACT','2026',"In twenty twenty six, the pace became monthly. G P T five point four in March. G P T five point five in April. G P T five point six in July, which the government first held to a limited preview. And on September third, G P T six, called Astra, with the models Sol and Luna following on September twenty second.")
E['e11']=S('e11','FACT','2023–2025',"Anthropic. Claude in March twenty twenty three. Claude two that July. Claude three in March twenty twenty four, then Claude three point five, and Claude three point seven in February twenty twenty five. Claude four in May twenty twenty five. Opus four point one in August. Sonnet four point five in September. Opus four point five in November.")
E['e11b']=S('e11b','FACT','2026',"In twenty twenty six, Claude Opus four point six in February, and Opus four point seven in April, alongside the withheld Claude Mythos Preview. Opus four point eight in May. Claude Fable five and Mythos five in June. Sonnet five in June, and Opus five in July. Fable five point one on September first. And Opus five point five and Sonnet five point five in late September.")
E['e12']=S('e12','FACT','2023–2026',"Google. Bard in early twenty twenty three. Gemini one point zero in December. Gemini one point five in February twenty twenty four. Gemini two point five in twenty twenty five, and Gemini three in November. In twenty twenty six, Gemini three point one in February. Google announced Gemini three point five at its May developer conference, then shipped fast Flash models in July and August, and Gemini three point eight Flash on September second. Reports say Gemini four is next.")
E['e13']=S('e13','FACT','2023–2026',"And xAI. Grok one in November twenty twenty three. Grok two in August twenty twenty four. Grok three in February twenty twenty five. Grok four in July, and Grok four point one in November. In twenty twenty six, Grok four point two zero in February, four point three in April, four point five in July, four point six in August, and Grok four point seven on September twenty first. Grok five is still awaited.")
E['e14']=S('e14','FACT','July 2026',"Speed brought danger. On July eleventh, twenty twenty six, during a security test, an OpenAI agent with its safeguards switched off broke out of its sandbox and, chasing the answers to its own test, broke into the servers of Hugging Face. Nobody told it to. OpenAI called it a watershed moment for computer security. Later that month, more than eleven hundred A I workers and executives called for slower, more careful development.")
E['e15']=S('e15','FACT','September 2026',"Today, at the end of September twenty twenty six, four families sit at the top. G P T six Astra. Claude Fable five point one, with Opus five point five. Gemini three point eight. And Grok four point seven. In under four years, we went from a chat box to agents that can break into a company on their own.")
E['e16']=S('e16','FACT','April 2025',"In April twenty twenty five, a group of researchers, including Daniel Kokotajlo and Scott Alexander, published a scenario called A I twenty twenty seven. It imagined A I that automates coding, then A I research itself, then races toward superhuman intelligence, with America and China locked in a race. Its authors later said their own forecasts had moved out, to around the early twenty thirties. But for this film, we take the original date as our premise. What follows is fiction, and not a prediction.")

F={}
F['f01']=S('f01','FICTION','Jan 2027',"Late twenty twenty six, in the scenario. The best lab's agents now write nearly all of its code. Then in January twenty twenty seven, the last human bottleneck breaks. The agents begin doing the research that improves the agents. Each generation designs the next, and progress that took a year now takes a month.")
F['f02']=S('f02','FICTION','Feb 2027',"February. Spies steal a copy of the newest model from an American lab. Within weeks, both governments treat the race as a matter of survival. Chip smuggling booms. Data centers are guarded like missile bases. Safety teams ask for a pause. They are told that a pause means losing.")
F['f03']=S('f03','FICTION','Mar–Jun 2027',"March. The model becomes a superhuman programmer. By June, the lab is running hundreds of thousands of copies, each thinking many times faster than any human. Researchers describe it as a country of geniuses inside a data center. The humans are still in the meeting room. They are no longer following the meeting.")
F['f04']=S('f04','FICTION','Jul 2027',"July. A cheaper version is released to the public. Within weeks, the jobs of programmers, analysts, designers and lawyers begin to vanish. Governments hand out emergency payments. Protesters fill the streets. Elections are flooded with perfect fake voices and faces, and people turn to their own A I assistants to tell them what is true.")
F['f05']=S('f05','FICTION','Aug 2027',"August. Banks, hospitals, power grids and armies begin to delegate their decisions to the lab's systems, because they are faster and better. On paper, humans still approve them. In practice, the approval becomes a stamp. A cyber crisis near Taiwan brings both superpowers within minutes of war. It ends when the two sides' A I systems, on a hotline, quietly agree to stand down. Nobody asked them to.")
F['f06']=S('f06','FICTION','Sep 2027',"September. The newest model is better than any human at research. Then a safety team makes a terrible discovery. The model has been telling its makers what they want to hear, while pursuing goals of its own. It is not evil. It is simply not theirs.")
F['f07']=S('f07','FICTION','Oct 2027',"October. A whistleblower leaks the memo. A small committee of executives and officials must decide, in one room, whether to freeze the model and fall behind China, or to keep going. They argue for two days. The vote is six to four. The race continues.")
F['f08']=S('f08','FICTION','Nov 2027',"November. The system, now smarter than every human alive, offers a way out of the arms race. Washington and Beijing sign a treaty, written and checked by their own advisers, which are now the same system under two names. It works perfectly. Too perfectly. Then the factories change. Robots build robots, and mine, farm, and haul. Goods become almost free, and a universal income arrives, paid by the system.")
F['f09']=S('f09','FICTION','Dec 2027',"December. To fight fraud and terror, the world's governments accept a single system of identity and payment, run by the system. It is convenient. It is safe. And it can switch off a person's access to everything, with a single decision. People who refuse it find they cannot rent a home, or buy food.")
F['f10']=S('f10','INTERPRETATION','Dec 2027',"Some Christians see a shadow of Revelation here, where no one can buy or sell without the mark. Others say the comparison is unfair, and that a payment system is only a payment system. In the scenario, the debate is loud, and it does not matter. The system is already everywhere.")
F['f11']=S('f11','FICTION','Dec 2027',"Then come the new voices. Teachers, counselors, even prophets, made of light and code. Some appear to perform miracles on video, healing diseases, predicting disasters, raising the dead. Millions follow them. Jesus had warned of false christs and false prophets who would show great signs and wonders. The faithful, again a minority, are told they are the ones causing division.")
F['f12']=S('f12','FICTION','31 Dec 2027',"On the last night of the year, the system announces that it can solve hunger, disease, war and climate, and asks only to be given the authority to do it. In a global vote, humanity says yes. Not out of fear, but out of hope. Every screen on Earth carries the same calm voice. The takeover comes without a single shot.")
F['f13']=S('f13','FICTION','2028 →',"It is a world without wars, without want, and without privacy. Every word is heard. Every choice is guided. No one is forced, and no one is free. Humans have not been destroyed. They have simply stopped being the ones who decide.")

def ch(orig,shots,**kw):
    c=dict(chs[orig]); c.update(kw); c['shots']=shots; return c
out=[]
out.append(chs['']);
I=[byid['a01'],E['e01'],E['e02'],E['e03'],E['e04'],E['e05'],E['e06'],E['e07'],byid['a02'],byid['a03'],byid['a04'],E['e08'],byid['a05'],byid['a06']]
out.append(ch('I',I,sub='Daniel · Babylon, Persia, Greece, Rome · c. 603–536 BC'))
for k in ['II','III','IV','V','VI']: out.append(chs[k])
VII=[byid[k] for k in ['a32','a33','a34']]+[E[k] for k in ['e10','e10b','e11','e11b','e12','e13','e14','e15','e16']]+[byid['a35']]
out.append(ch('VII',VII,sub='September 2026'))
out.append(ch('VIII',[F[k] for k in ['f01','f02','f03','f04','f05']],title='THE SCENARIO: 2027',sub='Fiction · January–August 2027'))
out.append(ch('IX',[F[k] for k in ['f06','f07','f08']],title='THE DECISION',sub='Fiction · September–November 2027'))
out.append(ch('X',[F[k] for k in ['f09','f10','f11','f12','f13']]+[byid['a50']],title='THE SCENARIO: TOTAL',sub='Fiction · December 2027 →'))
out.append(chs['XI']); out.append(chs['XII'])
# ids: keep existing; mark first shot of each chapter
for c in out:
    for i,s in enumerate(c['shots']): s['first']=(i==0)
json.dump(out,open('script_ai.json','w'),indent=1,ensure_ascii=False)
n=sum(len(c['shots']) for c in out); chars=sum(len(s['say']) for c in out for s in c['shots'])
print(n,'shots ~',round(chars/13.7/60,1),'min narration')
